### ISSUE TITLE
Addition - Add two numbers together

### ISSUE THREAD

**Issue by karl-henrik** [karl-henrik/qsec-calculatorservice#2]
Add an endpoint for addition in the maths controller. 

The endpoint should REQUIRE two numbers as the parameters.
The endpoint should SUPPORT integers and decimal numbers. 

2,4 should generate the response 6
11.5 and 12.5 should generate the response 24.0.

Related issues : #3

**Comment by theplastictoy** [comment]
@karl-henrik should this be GET or POST? Should this return JSON?

**Comment by karl-henrik** [comment]
POST with a JSON body. Preferably with an input object :-)

**Comment by karl-henrik** [comment]
Closed with pull request #11
