### ISSUE TITLE
Subtraction - Removes one number from the other

### ISSUE THREAD

**Issue by karl-henrik** [karl-henrik/qsec-calculatorservice#3]
Add an endpoint for subtraction in the maths controller.

The endpoint should REQUIRE two numbers as the parameters.
The endpoint should SUPPORT integers and decimal numbers.

Test data 

4,2 should generate the response 2.
11.5, 12.5 should generate the response -1

Related issues: #2

**Comment by haraldfianbakken** [comment]
I'll take this one
